image:
  name: google/cloud-sdk:416.0.0-alpine

variables:
  GOOGLE_CLOUD_REGION: asia-northeast1

stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9-slim
  script:
    - ./deploy/test.sh
  except:
    - tags

.gcloud_auth: &gcloud_auth
  before_script:
    - echo ${CI_JOB_JWT_V2} > .ci_jwt
    - gcloud iam workload-identity-pools create-cred-config ${GOOGLE_CLOUD_WORKLOAD_IDP} --service-account "sa-cicd@${GOOGLE_CLOUD_PROJECT}.iam.gserviceaccount.com" --credential-source-file .ci_jwt --output-file .cred.json
    - gcloud auth login --cred-file "$(pwd)/.cred.json"
    - gcloud auth list --filter=status:ACTIVE --format="value(account)"
    - gcloud config set project ${GOOGLE_CLOUD_PROJECT}

deploy-to-dev:
  stage: deploy
  <<: *gcloud_auth
  script:
    - echo ${GOOGLE_CLOUD_FIREBASE} > src/libs/config.py
    - gcloud builds submit --tag ${GOOGLE_CLOUD_REGION}-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/my-apps/streamlit:${CI_COMMIT_SHORT_SHA} src
    - gcloud run deploy dev-svc --image ${GOOGLE_CLOUD_REGION}-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/my-apps/streamlit:${CI_COMMIT_SHORT_SHA} --region "${GOOGLE_CLOUD_REGION}" --service-account "sa-app@${GOOGLE_CLOUD_PROJECT}.iam.gserviceaccount.com" --set-env-vars GCLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
  only:
    - main
