services:
  - docker:dind

image:
  name: google/cloud-sdk:416.0.0-alpine

variables:
  GOOGLECLOUD_REGION: asia-northeast1

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - python3 -m ensurepip --upgrade
    - ln -s /usr/bin/pip3 /usr/bin/pip
    - ./deploy/test.sh
  except:
    - tags

.gcloud_auth: &gcloud_auth
  before_script:
    - echo ${GOOGLECLOUD_SA_KEY} > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set project ${GOOGLECLOUD_PROJECT}
    - rm -rf key.json

deploy-to-dev:
  stage: deploy
  <<: *gcloud_auth
  script:
    - python3 -m ensurepip --upgrade
    - pip3 install poetry
    - cd src
    - poetry export --without dev --without-hashes --format=requirements.txt > requirements.txt
    - echo ${GOOGLECLOUD_FIREBASE} > libs/config.py
    - gcloud builds submit --pack image=${GOOGLECLOUD_REGION}-docker.pkg.dev/${GOOGLECLOUD_PROJECT}/my-apps/streamlit:${CI_COMMIT_SHORT_SHA} .
    - gcloud run deploy dev-svc --image ${GOOGLECLOUD_REGION}-docker.pkg.dev/${GOOGLECLOUD_PROJECT}/my-apps/streamlit:${CI_COMMIT_SHORT_SHA} --region "${GOOGLECLOUD_REGION}" --service-account "sa-app@${GOOGLECLOUD_PROJECT}.iam.gserviceaccount.com" --set-env-vars GCLOUD_PROJECT=${GOOGLECLOUD_PROJECT}
  only:
    - main
