steps:
  - id: 'config'
    name: bash
    script: echo "${FIREBASE_JS}" > src/libs/config.py
    secretEnv: ['FIREBASE_JS']

  - id: 'push'
    name: 'gcr.io/kaniko-project/executor:latest'
    args: ['--destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/my-apps/streamlit:$SHORT_SHA',
      '--context=dir://src', '--cache=true', '--cache-ttl=6h']

  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'dev-svc', '--region=asia-northeast1',
      '--image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/my-apps/streamlit:$SHORT_SHA',
      '--service-account=sa-app@$PROJECT_ID.iam.gserviceaccount.com',
      '--set-env-vars=GCLOUD_PROJECT=$PROJECT_ID']

  - id: 'test'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args: ['deploy/test.sh']
    waitFor: ['-']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/firebase-configs/versions/latest
    env: 'FIREBASE_JS'
