name: Release to dev

on:
  push:
    branches:
    - main

env:
  GOOGLE_CLOUD_REGION: "asia-northeast1"

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yaml

  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDP }}
        service_account: "sa-cicd@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Check the auth
      run: gcloud auth list --filter=status:ACTIVE --format="value(account)"

    - name: Create the firebase.js
      run: gcloud secrets versions access latest --secret firebase-configs > src/libs/config.py

    - name: Configure docker
      run: gcloud auth configure-docker ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev --quiet

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the image
      uses: docker/build-push-action@v3
      with:
        tags: ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/my-apps/streamlit:${{ github.sha }}
        context: src
        push: true
        provenance: true

    - name: Release to Dev
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: dev-svc
        region: ${{ env.GOOGLE_CLOUD_REGION }}
        image: ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/my-apps/streamlit:${{ github.sha }}
        env_vars: GCLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}
        flags: --service-account=sa-app@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com
